### ISSUE TITLE
How to install it in Linux or Mac

### ISSUE THREAD

**Issue by zhujuan0528** [liufeihong/Hyper-Upload-Server#2]
when I run the command "./hyupdsrv"
the terminal feedback:exec format error
我在linux下执行这个命令的时候会返回报错，打开这个命令发现全是乱码，希望能够提供比较完整的linux环境下安装手册

**Comment by lubalubalu** [comment]
你好，方便时可以加我QQ 交流，查看一下报错细节以便查找问题原因进行改进！
我的QQ: 1918098288


发自我的iPhone

------------------ Original ------------------
